# Data analysis

## Setup Google API

In [ ]:
# @title Mount google drive and read in the SERVICE_ACCOUNT_FILE  {"form-width":"20%"}

# @markdown ---
# @markdown
# @markdown The `SERVICE_ACCOUNT_FILE` path is stored as a secret in google colab. If you do not have this sotred on your colab, contact the Admin: Travis Kregear at tkregear@pdx.edu
# @markdown
# @markdown '/content/drive/Shareddrives/AI_Shared/AI Colabs/Admin Files/service_account.json'
# @markdown
# @markdown The `PACKAGE_PATH` path is stored as a secret in google colab.
# @markdown `/content/drive/Shareddrives/AI_Shared/AI Colabs/packages`
# @markdown
# @markdown If you do not have these sotred on your colab, contact the Admin: Travis Kregear at tkregear@pdx.edu

# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# load SERVICE_ACCOUNT_FILE
from google.colab import userdata

SERVICE_ACCOUNT_FILE = userdata.get('SERVICE_ACCOUNT_FILE')
PACKAGE_PATH = userdata.get('PACKAGE_PATH')


# @title ## Install pyDrive  {"form-width":"20%"}

# @markdown ---
# @markdown Installing PyDrive
# @markdown
# @markdown Thie is necessary if using the Google API to call files by their file_id

# !pip install PyDrive

import sys
# 2. Tell Python to look in your custom folder
sys.path.append(PACKAGE_PATH)

# 3. Import your file!
from GoogleFunctions import GoogleDocumentManager, extract_file_id

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Read in data

data read in will be merged using the `user` column

- consent file
- transcript data

In [ ]:

# @title Read in consent file {"form-width":"20%"}
consent_file_link = "https://drive.google.com/file/d/1OBOz23ByNoxk7L2-DMKa3rhR_U9G56b-/view?usp=drive_link" # @param {"type":"string"}
consent_file_link_id = extract_file_id(consent_file_link)
show_consent = True # @param {"type":"boolean"}

GDM = GoogleDocumentManager(SERVICE_ACCOUNT_FILE)

print(f"Reading in csv file. id={consent_file_link_id}")
consent_df = GDM.read_csv(
    document_id=consent_file_link_id,
    file_type = 'csv',
    )
if show_consent:
  display(consent_df)

Google Drive API service built successfully.
Reading in csv file. id=1OBOz23ByNoxk7L2-DMKa3rhR_U9G56b-

     user  consent
0     241    False
1     141     True
2     156     True
3     115    False
4     177     True
..    ...      ...
156   189     True
157   216    False
158   264    False
159    86     True
160   267     True

[161 rows x 2 columns]

In [ ]:

# @title Read in survey file {"form-width":"20%"}
survey_file_link = "https://drive.google.com/file/d/1J_k6_tVPGf5lY6Pm2YoeKzm-WGwlFd8C/view?usp=drive_link" # @param {"type":"string"}
survey_file_link_id = extract_file_id(survey_file_link)
show_survey = True # @param {"type":"boolean"}

GDM = GoogleDocumentManager(SERVICE_ACCOUNT_FILE)

print(f"Reading in csv file. id={survey_file_link_id}")
survey_df = GDM.read_csv(
    document_id=survey_file_link_id,
    file_type = 'csv',
    )
if show_survey:
  display(survey_df)

Google Drive API service built successfully.
Reading in csv file. id=1J_k6_tVPGf5lY6Pm2YoeKzm-WGwlFd8C

,user,Timestamp,Which Resources did you use during this lab course? (Select all that apply.),Did you use the AI Assistant feature in the Lab Notebook during this course?,Using the AI Assistant helped me better understand the lab material.,Please describe how the AI Assistant helped you better understand the lab material.,Please describe how the AI Assistant was NOT helpful or confusing.,Did you ever share your spreadsheet data with the AI assistant?,"When the AI Assistant used your data, how would you rate the quality of its responses compared to when it did not use your data?",Did the AI Assistant provide you with incorrect information when it had access to your data?,...,Did you use a different LLM (outside the Lab Notebook) while working on your labs?,Which LLM platform did you prefer to use during this lab course?,The other LLM responses were helpful for answering lab questions.,Provide a brief description of how you utilized the LLM in the context of this course.,"Compared to me, I think my classmates probably use the AI Assistant in the Lab Notebook…","Compared to me, I think my classmates probably use other LLMs for physics labs…","In your opinion and experience, what is the most effective way to use LLMs for learning?",The Lab Notebook interface was easy to use.,"Reflecting on your experience with the Lab Notebook, describe one feature you liked.","Reflecting on your experience with the Lab Notebook, describe one area you think could be improved."
0,103,12/2/2025 22:08:58,"Physics Textbook, TA Office Hours, Other Class...",Yes,Neutral,I dont think it really helped. half the time i...,More times than i could count it would not giv...,No,NaN,NaN,...,No,NaN,NaN,NaN,more than I do.,more than I do.,I dont know i didnt use them. I just went to o...,Strongly Agree,I like that google docs and sheets is automati...,the AI definitely needs more work. Having to w...
1,267,12/10/2025 18:09:05,"Physics Textbook, Internet Web Search, Other C...",Yes,Agree,Effectively alble to verify my outputs with ex...,I believe it has been helpful,Yes,Very Good,No,...,No,NaN,NaN,NaN,about the same as I do.,about the same as I do.,Verification of information and explanation of...,Strongly Agree,Thoughtful response under each question,NaN
2,142,12/3/2025 22:05:11,"Internet Web Search, Other Classmates/Lab Part...",Yes,Agree,It helped give clarity and helped verify wheth...,Sometimes it would take 5+ minutes to think of...,No,NaN,NaN,...,No,NaN,NaN,NaN,about the same as I do.,more than I do.,"In my experience, I usually use it to get exam...",Neutral,I liked how I didn't have to learn how to use ...,Interface is too small/cluttered; I was better...
3,143,12/2/2025 22:42:24,"Physics Textbook, Internet Web Search, Other C...",No,NaN,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,more than I do.,more than I do.,I like to use it to explain concepts for me by...,Strongly Agree,I liked how it was set up to be automatically ...,I think it should be able to open up into a di...
4,129,12/6/2025 8:56:21,"Physics Textbook, Internet Web Search",No,NaN,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,about the same as I do.,more than I do.,As a means of gathering information before del...,Neutral,I liked being able to tab between my data and ...,I think the window for the lab notebook should...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,205,11/19/2025 14:50:16,Lab notebook,No,NaN,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,Agree,I liked that I could switch between the lab ma...,NaN
129,205,11/19/2025 14:52:01,Lab notebook,No,NaN,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,Agree,I liked that I was able to switch between the ...,None.
130,79,12/2/2025 14:26:20,"Physics Textbook, Internet Web Search, Other C...",Yes,Agree,I could ask it clarifying questions regarding ...,Sometimes it did not completely answer my ques...,Yes,Very Good,No,...,No,NaN,NaN,NaN,about the same as I do.,more than I do.,Have it help you understand how to set up diff...,Agree,being able to continue with the next question ...,More in-depth responses to deeper questions ra...
131,133,11/21/2025 12:45:33,"Physics Textbook, Internet Web Search",No,NaN,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,Disagree,It made google docs for me,"I didn't use any other part of it, so I don't ..."
132,261,12/3/2025 20:28:31,"Physics Textbook, Internet Web Search",Yes,Agree,I mostly used the AI assistant on the first la...,Sometimes the AI assistant was a bit confusing...,No,NaN,NaN,...,No,NaN,NaN,NaN,about the same as I do.,more than I do.,I think the best way to use LLMs for learning ...,Agree,I liked how easy and convenient it was to move...,"Honestly, I don’t really have anything I would..."

In [ ]:
# @title Combine consent data into transcript data and split up question column
import pandas as pd

combined_df = pd.merge(consent_df, survey_df, on='user', how='inner')

print("Consent data has been merged with DataFrame:")
# display(combined_df.head())

Consent data has been merged with DataFrame:

## Analysis

In [ ]:
from google.colab import sheets

# @title Create Interactive Sheet and optionally move to a specific folder {"form-width":"20%"}

sheet_name = "Interactive sheet" # @param {"type":"string"}
create_google_sheet = False # @param {"type":"boolean"}
if create_google_sheet:

  # Create the interactive sheet
  sheet_object = sheets.InteractiveSheet(title=sheet_name, include_column_headers=True, df=combined_df)
else:
  display(combined_df)

,user,consent,Timestamp,Which Resources did you use during this lab course? (Select all that apply.),Did you use the AI Assistant feature in the Lab Notebook during this course?,Using the AI Assistant helped me better understand the lab material.,Please describe how the AI Assistant helped you better understand the lab material.,Please describe how the AI Assistant was NOT helpful or confusing.,Did you ever share your spreadsheet data with the AI assistant?,"When the AI Assistant used your data, how would you rate the quality of its responses compared to when it did not use your data?",...,Did you use a different LLM (outside the Lab Notebook) while working on your labs?,Which LLM platform did you prefer to use during this lab course?,The other LLM responses were helpful for answering lab questions.,Provide a brief description of how you utilized the LLM in the context of this course.,"Compared to me, I think my classmates probably use the AI Assistant in the Lab Notebook…","Compared to me, I think my classmates probably use other LLMs for physics labs…","In your opinion and experience, what is the most effective way to use LLMs for learning?",The Lab Notebook interface was easy to use.,"Reflecting on your experience with the Lab Notebook, describe one feature you liked.","Reflecting on your experience with the Lab Notebook, describe one area you think could be improved."
0,241,False,11/21/2025 19:00:59,"Internet Web Search, Other Classmates/Lab Part...",No,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,about the same as I do.,about the same as I do.,If you were to be confused on a certain subjec...,Agree,I liked how easily I could switch between tabs...,NaN
1,141,True,11/30/2025 17:28:43,"Physics Textbook, Internet Web Search",Yes,Neutral,Helps for definitions and checking if you get ...,Does not always make sense for answers and say...,No,NaN,...,No,NaN,NaN,NaN,more than I do.,about the same as I do.,Helps give you an organized topic outline for ...,Agree,I liked how everything was together instead of...,The AI tool says the same thing sometimes whic...
2,141,True,12/2/2025 22:03:48,"Physics Textbook, Internet Web Search",Yes,Neutral,It helped with quick definitions and seeing if...,It was confusing sometimes because it would gi...,No,NaN,...,Yes,ChatGPT,Neutral,I used chatgpt to help me with structure and o...,more than I do.,about the same as I do.,For help with organizing data and reports.,Agree,I liked how everything was packed into one pro...,I think the AI responses could be improved.
3,156,True,11/20/2025 22:26:34,"Physics Textbook, Internet Web Search",Yes,Neutral,It did not,At times the answer was elongated and confusin...,No,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,Agree,That the Lab Notebook automatically created a ...,Stop forcing AI into everything lolz the Lab N...
4,115,False,11/19/2025 13:40:29,"Physics Textbook, Internet Web Search",No,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,Agree,"With using the online Lab Notebook, one featur...",One area that I think could be improved was th...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,243,True,12/2/2025 11:53:46,Physics Textbook,Yes,Agree,it help me make sure that my lab question are ...,it was helpful,No,NaN,...,No,NaN,NaN,NaN,about the same as I do.,about the same as I do.,im not sure,Agree,how organized it is to follow up the procedure,nothing
128,263,True,12/2/2025 13:35:36,"Physics Textbook, TA Office Hours",No,NaN,NaN,NaN,NaN,NaN,...,No,NaN,NaN,NaN,more than I do.,more than I do.,I don't find them helpful just because it neve...,Neutral,I really liked that i had acces to everything ...,"Using excell instead of google sheets, and usi..."
129,166,False,11/30/2025 22:46:55,Internet Web Search,Yes,Agree,"I mainly asked what equations I should use, as...",The only thing I can think of is I sometimes a...,No,NaN,...,No,NaN,NaN,NaN,less than I do.,about the same as I do.,I think it's most useful in terms of understan...,Strongly Agree,I thought the lab was easy to follow and the s...,"for the formal labs, I think it should have be..."
130,189,True,12/2/2025 18:03:55,Internet Web Search,Yes,Strongly agree,It told me how to report my answer properly an...,Sometimes it did give me incorrect answers but...,No,NaN,...,Yes,ChatGPT,Agree,Using chatgpt was more insightful to tell me h...,I haven't talked to anyone in the class lab un...,I don't know/,Most effective way for me was seeing how to pe...,Agree,Ai for the specific lab questions i think i re...,have the ai in sperate place because it's real...
131,267,True,12/10/2025 18:09:05,"Physics Textbook, Internet Web Search, Other C...",Yes,Agree,Effectively alble to verify my outputs with ex...,I believe it has been helpful,Yes,Very Good,...,No,NaN,NaN,NaN,about the same as I do.,about the same as I do.,Verification of information and explanation of...,Strongly Agree,Thoughtful response under each question,NaN

In [ ]:
combined_df.to_csv('combined_data.csv', index=False)
print('combined_df saved to combined_data.csv')

combined_df saved to combined_data.csv